parameters:
    database_host: localhost
    database_port: '3306'
    database_name: charis
    database_user: charis
    database_password: Pa55word
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: gigantic222@gmail.com
    mailer_sender_name: b2c
    mailer_password: null
    secret: 5dfd4a4344a4816a859cddaf7926e0107
    database_driver: pdo_mysql
    database_path: null
